#!/bin/bash
# This is the first shell program of the day

echo "Hello $LOGNAME, it's nice to talk to you."
echo "Your present working directory is `pwd`."
echo "You are working on a machine called `uname -n`."
echo "Here is a list of your files."
ls
echo "Bye for now $LOGNAME. The time is `date +%T`!"
