#!/bin/bash

# Scriptname: printer_check
# Script to clear a hung-up printer

if [ $LOGNAME != root ]
then
    echo "Must have root privileges to run this program"
    exit 1
fi

# Here document. Note: 
#1. The last EOF 一定要顶格写
#2. The last EOF 后面不能有任何的字符包括空格。
cat << EOF
    Warning: All jobs in the printer queue will be removed.
    Please turn off the printer now. Press return when you are ready to continue.
    Otherwise press Control C.
EOF

read JUNK
echo

/etc/rc.d/init.d/lpd stop # Stop the printer

echo -e "\n Ploease turn the printer on now."

echo "Press Enter to continue."

read JUNK

echo

/etc/rc.d/init.d/lpd start
